# Generated by Django 6.0.3 on 2026-04-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Write Item Name",
                        max_length=100,
                        verbose_name="Item Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Write Item Description",
                        max_length=500,
                        verbose_name="Item Description",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Write Item Price", verbose_name="Item Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Write Item Currency",
                        max_length=3,
                        verbose_name="Item Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
    ]
